name = "felixdulce-cms"
main = "src/index.ts"
compatibility_date = "2026-07-14"
compatibility_flags = ["nodejs_compat"]
account_id = "66ac946cc319414ca3b5350df514521e"
workers_dev = true

# This forces esbuild to bypass the missing local workspace paths
rules = [
  { type = "ESModule", converters = ["esm"], globs = ["**/*.js"] }
]

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "felixdulce-db"
database_id = "39deb735-76ef-40e8-ba5e-8b7fc3ac6822"
